import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ShowNav from "./showNav";

export const metadata = {
  title: "Zuccess Testing Console",
  description: "Generated by Zuccess Team",
  icons: {
    icon: "/fav.png",
  },
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ShowNav />
        {children}
      </body>
    </html>
  );
}
